### ISSUE TITLE
Occasional lag spikes to 0fps that make the game unplayable

### ISSUE THREAD

**Issue by SuicSoft** [daipenger/Sound-Physics#2] opened 2017-04-18 14:39 UTC
When using this mod sometimes the game lags to 0fps for about a minute.

**Comment by daipenger** [comment] 2017-04-18 15:26
Cannot confirm, raytracing is capped at 250 blocks range and usually does not take longer than 1ms on my system.
Can you turn on performance and occlussion debugging and profile it?

**Comment by Tsoccerguy3** [comment] 2017-04-19 02:16
System specs 
amount of memory allocated to Minecraft (Java VM)
list of mods installed would help

**Comment by SuicSoft** [comment] 2017-04-19 14:57
@Tsoccerguy3 

CPU : AMD A8-4500M
GPU : Radeon HD 7640G
RAM : 6GB DDR3 (2GB allocated to Minecraft)

Mods installed : Optifine , betterFPS and foamfix

It doesn't seem to be a problem with my computer being laggy since it only happens sometimes (while im playing 0fps for about a minute and then back to normal for a 5 - 30 minutes). Seems like something with Java GC.

@daipenger Where are those logs stored ? What CPU etc do you have 

My Minecraft FPS is mostly over 100 in local worlds and around 40 on a laggy SMP server

**Comment by daipenger** [comment] 2017-04-19 17:07
FoamFix that does some serious messing around, combined with BetterFPS and OptiFine... Works, but I call that an explosive mixture

My Specs, because you asked: Core i5 6600K, 1GB allocated to MC (I don't play heavy modpacks)

Go into the Mod settings of SoundPhysics, into Misc and there you can enable performance debugging and occlussion debugging.
It will write a lot of stuff into the console/launcher log but I is worth looking into it when your game runs normal and comparing it when your game gets laggy. I would start by just enabling performance debugging. If the run times stay the same, you can stop, because it is not related to SoundPhysics. If they won't you will have to investigate a bit further (occlussion debugging)

**Comment by SuicSoft** [comment] 2017-04-23 15:05
@daipenger Normally the sound calculation time is 1 - 4ms and when it lags to 0fps the calculation time is 100 - 200ms and any ideas on how to fix this.

Try to reduce calculation time too (when running normally not lagging) by multithreading or compute shaders. The mod seems to need a very high clocked CPU to run smoothly.

Maybe running sound on another thread is also a good idea so it wont affect FPS when it lags then.I didn't have this problem on 1.11 (but i was using Linux then :P)

**Comment by daipenger** [comment] 2017-04-24 14:17
With multithreading, compute shaders and whatnot you are only working around some unknown bug and not fixing the problem. There are also other problems:
- Compute shaders: Total overkill, a lot of effort to put in for little to no benefits.
- Multithreading: Precalculating the environment is computationally infeasible. (in a way that resembles the current algorithm) The only way would be by computing sounds asynchronically. That however would delay the sound, which is not wanted.

I think you are suffering from something different: 1-4ms is what I expected for your CPU. Doesn't stall the game loop by a whole lot and should work overall.

- TLDR: CPU keeps its clock and is not overheating? No Windows Update/antivirus? Hard drive not damaged?

The algorithm does a lot of raytracing and depends on the world being loaded. I suspect that FoamFix plays a role with chunk loading/unloading and may stall something from time to time. But I wouldn't use FoamFix in the first place: The JVM knows what it's doing. It's the result of many years of expert effort and knowledge by a lot of companies. FoamFix tries to mess with stuff that is normally the domain of the JVM. That's not only dangerous, it's naive and doomed to contain bugs.

- TLDR: Remove FoamFix and try it again. It should be fine to keep BetterFPS.

If nothing helps you will have to profile your game: https://visualvm.github.io/
I cannot reproduce your problem. The mod runs fine for me.

**Comment by SuicSoft** [comment] 2017-04-25 14:37
@daipenger CPU does keep it's clock (**2.3 ghz boost with all cores active**) and is not overheating (**81c** normal for laptops). Windows update isn't running and Windows Defender isn't eating up CPU. Hard drive perfect too has no **S.M.A.R.T** errors.

I tried removing FoamFix (I never really needed it anyways) and it fixes the lag spikes when playing normal survival. But still when flying with creative or elytra I get very short (1 second) lags spikes to around 10fps and sound stutters.

Also does the sound calculation time affect FPS of the game ?

**Comment by daipenger** [comment] 2017-04-25 15:17
That's good to hear! :)

The remaining lag spikes when flying around may not come from this mod solely. After all, your CPU is designed for a laptop with only 35W TDP. You simply cannot expect a lot from it.

> Also does the sound calculation time affect FPS of the game ?

The mod only comes to play when a sound plays, that's the only time it takes ressources. It then hands of the determined parameters to OpenAL's EFX to play the sound with reverb, low-pass filtering etc. EFX of course also takes ressources on the CPU. If your sound stutters, your CPU is running on the limit.

So, usually it won't affect FPS because your game loop can recover quickly enough from the added load on the game tick. But if you spam sounds or your CPU runs on the limit in the first place, it will decrease FPS.

**Comment by SuicSoft** [comment] 2017-04-26 03:44
@daipenger The lag spikes and stuttering don't happen without the mod. Does this mod require a very powerful CPU ?

**Comment by daipenger** [comment] 2017-04-26 16:28
I would say no. One of my friends owns a Sandy Bridge CPU that was only average back when it was new. (some kind of i3 if I'm not mistaken) But, the mod still runs well.

My last idea would be checking if your sound drivers are up to date and that they are not the standard Microsoft ones. Even though hardware support for EFX has become rare, it may make a difference.
I have already shown you VisualVM for profiling. That tool may also help.

But as we are getting to nowhere here, I will close this soon and once I have the time I will try to optimize the mod even further. But I don't see a lot of potential anymore.

**Closed as completed** 2017-05-07 11:06 UTC
